DOC: local testing deployent documentation extended in README
ContactEngineering/topobank-stack-development pull request #5
Opened 2023-01-20 09:39 UTC by jotelha

2023-01-23 13:33 UTC, mcrot commented on README.rst
> +You are now able to log in with via ORCID and upload data, but you will not have access to any analysis functionality.
Here I would add "so far", so it's clear, this can be added.

2023-01-23 13:34 UTC, mcrot commented on README.rst
> +   Example: If the URL is :code:`https://contact.engineering/users/anna/`, then :code:`your_username` is :code:`anna`.
No, the url with `localhost` is correct. The username given `contact.engineering` can differ and this is about the local development system.

2023-01-23 13:36 UTC, mcrot commented on README.rst
> +:code:`requirements/development.txt` by providing :code:`pip-compile`
Why prodiving `pip-compile`? Running `make` already calls `pip-compile`.

2023-01-23 13:38 UTC, mcrot requested changes
The old url was correct for the purpose of the readme, and I've 
propose some changes. Please see comments...

2023-01-25 16:11 UTC, jotelha commented on README.rst
> +:code:`requirements/development.txt` by providing :code:`pip-compile`
Yes, make calls it, but does not provide it. Won't run if it's not there.

2023-01-25 16:11 UTC, jotelha commented on README.rst
> +   Example: If the URL is :code:`https://contact.engineering/users/anna/`, then :code:`your_username` is :code:`anna`.
That was something that reentered because of diverging branches

2023-01-25 19:22 UTC, jotelha commented
@mcrot addressed your comments and renamed the pull request. Avoids embedding requirements file in container images.

2023-01-26 08:54 UTC, jotelha reviewed
Addressed all comments.

2023-02-06 20:50 UTC, merged